clone :
   depth : 1
kind: pipeline
name : nexus
steps:
 - name: sdm845
   image: panchajanya1999/archlinux:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - bash build.sh
